language: java

sudo: true

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - ./gradlew assemble --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)

