install: gradle wrapper --gradle-version 4.6
language: java
+jdk: oraclejdk8
sudo: true
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  artifacts:
      path:
      - /home/travis/build/project/Sea_battle/build/libs/